# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: test
  pool: 5
  username: root
  password: root
  host: <%= ENV["DB_HOST"] %> #this is host for container with mysql
  port: 3306
