# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 786cc3087d1070da303c43972e352f90a6b07808bd0d3763c23c2957c820db9e2aa8ae55b106adf815c3bcc9337280e8e88f45745c0fed7eee41a0a3e811ace2
  test: <%= ENV["TEST"] %>

test:
  secret_key_base: d647b6b3e1922f26fcd966e13c12924427c43b12126812d11c3478381a95b077d68e86e03120190aba4c0a62b52e8a3c74a758cf96db731c02b5362de81f1f00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
